name: Detectar pr

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  detectar_PR:
    runs-on: ubuntu-latest
    
    steps:
    - name: Download Source
      uses: actions/checkout@v4
      
    - name: detectar_pr
      if: github.event_name == 'pull_request'
      run: echo "Â¡Se ha detectado un pull_request!"  